service: serverless-boilerplate

custom:
    stage: ${opt:stage, 'development'}
    region: ${opt:region, 'us-west-2'}
    serverless-offline:
        httpPort: 4000
        noPrependStageInUrl: true
        reloadHandler: true
    esbuild:
        bundle: true
        minify: false
        packager: yarn
        packagerOptions:
            scripts:
                - yarn clean
        watch:
            pattern: ['src/**/*.ts'] # default .
            ignore: ['.serverless/**/*', '.build', 'dist', 'node_modules']

provider:
    name: aws
    runtime: nodejs18.x
    memorySize: 512
    timeout: 10
    logRetentionInDays: 90
    logs:
        httpApi: true
    httpApi:
        cors: true

functions:
    app:
        handler: src/handler.handler
        events:
            - httpApi:
                  path: '/{proxy+}'
                  method: '*'

package:
    individually: true

plugins:
    - serverless-dotenv-plugin
    - serverless-esbuild
    - serverless-offline
